apiVersion: v1
kind: ConfigMap
metadata:
  name: event-platform-config
  namespace: event-platform
data:
  APP_ENV: "production"
  KAFKA_BROKERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "event_platform"
  MONGODB_DATABASE: "event_platform"
